### ISSUE TITLE
Timer does not pause if game is paused

### ISSUE THREAD

**Issue by tahabhagat** [LOCKhart07/snake-game#1]
When game is paused, timer keeps running which gives incorrect results on the scoreboard

Fix: Pause the timer when the game is paused

**Comment by tahabhagat** [comment]
@LOCKhart07 please take this up on priority

**Comment by LOCKhart07** [comment]
Fixed with 0ebdf6548f7d66c213f765ed9907797b0adfdaa0 & 64e169b7776cc295da7ef91806356bc0be111059
